site_name: McNative Documentation
site_description:
site_url: http://docs.mcnative.org/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
  extra_css:
    - stylesheets/bootstrap-grid.min.css
    - stylesheets/style.css
  icon:
    repo: fontawesome/brands/github
  logo: https://content.pretronic.net/products/mcnative/logo.png
  favicon: https://content.pretronic.net/products/mcnative/logo.png
  palette:
    scheme: preference
    primary: 'deep orange'
    accent: 'deep orange'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - admonition
  - meta
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      clickable_checkbox: false
  - toc:
      permalink: true
      toc_depth: 3

plugins:
  - search
  - git-revision-date

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/bootstrap-grid.min.css
  - stylesheets/style.css


edit_uri: https://github.com/McNative/McNative-Documentation/edit/main/projects/home/docs/
